# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
services:
    app.jwt_auth:
        class: AppBundle\Services\JwtAuth
        arguments: ["@doctrine.orm.entity_manager"]
        
    app.helpers:
        class: AppBundle\Services\Helpers
        arguments: ["@app.jwt_auth"]
        