default_index:
    path: /
    defaults: {_controller: "AppBundle:Default:index"}
    methods: GET

pruebas_index:
    path: /pruebas
    defaults: {_controller: "AppBundle:Default:pruebas"}
    methods: GET